# -*- coding: utf-8 -*-
"""new code 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EpEaG2ixBQP8YwUC--ZdfwtZePJCvivT

Install
"""

import time
CELL1_START = time.time()

!pip install xgboost lightgbm imbalanced-learn bayesian-optimization ctgan psutil joblib --quiet

CELL1_END = time.time()
print(f"Cell 1 done in {(CELL1_END - CELL1_START)/60:.1f} min")

""" Imports"""

CELL2_START = time.time()

import os, time, warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestClassifier, VotingClassifier
from sklearn.feature_selection import mutual_info_classif
from sklearn.metrics import (accuracy_score, classification_report,
                              precision_score, recall_score,
                              f1_score, roc_auc_score)
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from ctgan import CTGAN
from bayes_opt import BayesianOptimization
import joblib

warnings.filterwarnings('ignore')
np.random.seed(42)

CELL2_END = time.time()
print(f"Cell 2 done in {(CELL2_END - CELL2_START):.1f} sec")

""" Mount Drive"""

CELL3_START = time.time()

from google.colab import drive
drive.mount('/content/drive')

CELL3_END = time.time()
print(f"Cell 3 done in {(CELL3_END - CELL3_START):.1f} sec")

"""Config"""

BASE      = '/content/drive/MyDrive/MyDrive/rosebox_ids'
SAVE_BASE = f'{BASE}/models/x-iiotid'
os.makedirs(SAVE_BASE, exist_ok=True)

SAMPLES_PER_FILE = 12000
TOP_N        = 40
MAX_FEATURES = 70
FEATURE_STEP = 2
PATIENCE     = 5
BO_INIT      = 2
BO_ITER      = 8

CFG = {
    'path'      : f'{BASE}/x-iiotid/X-IIoTID dataset.csv',
    'label_col' : 'class1',
    'drop_cols' : ['Date', 'Timestamp', 'Scr_IP', 'Des_IP',
                   'Scr_port', 'Des_port', 'class2', 'class3'],
}
print("done")

"""Load"""

print("[1] Loading X-IIoTID...")
df = pd.read_csv(CFG['path'], low_memory=False,
                 encoding='latin1', on_bad_lines='skip')
df.columns = df.columns.str.strip()

if len(df) > SAMPLES_PER_FILE * 10:
    df = df.sample(SAMPLES_PER_FILE * 10, random_state=42)

print(f'shape: {df.shape}')
print(f'label counts:\n{df[CFG["label_col"]].value_counts().to_string()}')

"""Clean"""

print("[2] Cleaning...")
drop = [c for c in CFG['drop_cols'] if c in df.columns]
df   = df.drop(columns=drop)

df.replace([np.inf, -np.inf], np.nan, inplace=True)
before = len(df)
df.dropna(inplace=True)

non_label = [c for c in df.columns if c != CFG['label_col']]
zero_var  = [c for c in non_label if df[c].nunique() <= 1]
df.drop(columns=zero_var, inplace=True)

print(f'dropped cols     : {len(drop)}')
print(f'removed NaN rows : {before - len(df)}')
print(f'zero-var removed : {len(zero_var)}')
print(f'clean shape      : {df.shape}')

"""Encode & Split"""

print("[3] Encoding & Splitting...")
le = LabelEncoder()
df[CFG['label_col']] = le.fit_transform(df[CFG['label_col']].astype(str))

X = df.drop(CFG['label_col'], axis=1).apply(pd.to_numeric, errors='coerce').fillna(0)
y = df[CFG['label_col']]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, stratify=y, random_state=42)

print(f'classes ({len(le.classes_)}): {list(le.classes_)}')
print(f'train : {X_train.shape}')
print(f'test  : {X_test.shape}')

"""Feature Selection"""

print("[4] Feature Selection...")

print('  RF importance...')
rf = RandomForestClassifier(n_estimators=100, n_jobs=-1, random_state=42)
rf.fit(X_train, y_train)
rf_scores = pd.Series(rf.feature_importances_,
                      index=X_train.columns).sort_values(ascending=False)

print('  Mutual information...')
mi_scores = pd.Series(
    mutual_info_classif(X_train, y_train, random_state=42),
    index=X_train.columns).sort_values(ascending=False)

combined = list(set(rf_scores.head(TOP_N).index) & set(mi_scores.head(TOP_N).index))
print(f'  agreed: {len(combined)} features')

ranked = [f for f in rf_scores.index if f in combined]
cap    = min(MAX_FEATURES, len(ranked))
steps  = list(range(FEATURE_STEP, cap + 1, FEATURE_STEP))
if cap not in steps:
    steps.append(cap)

best_acc, best_n, no_improve = 0, 2, 0
for n in steps:
    sel = ranked[:n]
    m   = XGBClassifier(n_estimators=100, max_depth=6, learning_rate=0.1,
                        eval_metric='mlogloss', tree_method='hist',
                        device='cuda', verbosity=0)
    m.fit(X_train[sel], y_train)
    acc = accuracy_score(y_test, m.predict(X_test[sel]))
    if acc > best_acc:
        best_acc, best_n, no_improve = acc, n, 0
        print(f'    n={n} acc={acc:.5f} <-- best')
    else:
        no_improve += 1
        print(f'    n={n} acc={acc:.5f} no_gain={no_improve}/{PATIENCE}')
        if no_improve >= PATIENCE:
            print('    early stop')
            break

selected_features = ranked[:best_n]
print(f'\noptimal features : {best_n}')
print(f'selected         : {selected_features}')

"""CTGAN Balancing"""

print("[5] CTGAN Balancing...")

X_df = pd.DataFrame(X_train[selected_features].values, columns=selected_features)
X_df['Label'] = y_train.values

majority   = max(Counter(y_train).values())
minorities = [c for c, cnt in Counter(y_train).items() if cnt < majority]
print(f'majority count : {majority}')
print(f'minorities     : {len(minorities)}')

synths = []
for cls in minorities:
    cls_data = X_df[X_df['Label'] == cls].drop('Label', axis=1)
    needed   = majority - len(cls_data)
    if len(cls_data) < 10:
        print(f'  class {cls}: too few samples, skipping')
        continue
    print(f'  class {cls}: {len(cls_data)} rows -> +{needed} synthetic')
    ctgan = CTGAN(epochs=30, verbose=False)
    ctgan.fit(cls_data)
    syn = ctgan.sample(needed)
    syn['Label'] = cls
    synths.append(syn)

aug      = pd.concat([X_df] + synths, ignore_index=True) if synths else X_df.copy()
X_tr_bal = aug.drop('Label', axis=1).values
y_tr_bal = aug['Label'].values
X_te_sel = np.array(X_test[selected_features])

print(f'balanced shape : {X_tr_bal.shape}')
print(f'class counts   : {Counter(y_tr_bal)}')

"""Bayesian Optimization"""

print("[6] Bayesian Optimization...")
y_te = np.array(y_test)

def xgb_eval(max_depth, learning_rate, n_estimators, subsample,
             colsample_bytree, min_child_weight, reg_alpha, reg_lambda):
    m = XGBClassifier(
        max_depth=int(max_depth), learning_rate=learning_rate,
        n_estimators=int(n_estimators), subsample=subsample,
        colsample_bytree=colsample_bytree,
        min_child_weight=int(min_child_weight),
        reg_alpha=reg_alpha, reg_lambda=reg_lambda,
        eval_metric='mlogloss', tree_method='hist',
        device='cuda', verbosity=0, n_jobs=-1)
    m.fit(X_tr_bal, y_tr_bal)
    return accuracy_score(y_te, m.predict(X_te_sel))

opt = BayesianOptimization(f=xgb_eval,
    pbounds={
        'max_depth'       : (3, 8),
        'learning_rate'   : (0.01, 1.0),
        'n_estimators'    : (50, 100),
        'subsample'       : (0.5, 1.0),
        'colsample_bytree': (0.5, 1.0),
        'min_child_weight': (0, 10),
        'reg_alpha'       : (1e-9, 1.0),
        'reg_lambda'      : (1e-9, 100),
    }, random_state=42, verbose=2)

opt.maximize(init_points=BO_INIT, n_iter=BO_ITER)
best = opt.max['params']
print(f'\nBO best accuracy : {opt.max["target"]:.5f}')
print('best params:')
for k, v in best.items():
    print(f'  {k}: {round(v, 5)}')

""" Train Ensemble"""

print("[7] Training Ensemble...")

xgb_final = XGBClassifier(
    max_depth=int(best['max_depth']),
    learning_rate=best['learning_rate'],
    n_estimators=int(best['n_estimators']),
    subsample=best['subsample'],
    colsample_bytree=best['colsample_bytree'],
    min_child_weight=int(best['min_child_weight']),
    reg_alpha=best['reg_alpha'],
    reg_lambda=best['reg_lambda'],
    eval_metric='mlogloss', tree_method='hist',
    device='cuda', verbosity=0)
xgb_final.fit(X_tr_bal, y_tr_bal)
print('  XGBoost done')

lgbm = LGBMClassifier(n_estimators=300, learning_rate=0.05, num_leaves=63,
                      is_unbalance=True, n_jobs=-1, random_state=42, verbose=-1)
lgbm.fit(X_tr_bal, y_tr_bal)
print('  LightGBM done')

rf_final = RandomForestClassifier(n_estimators=200, n_jobs=-1, random_state=42)
rf_final.fit(X_tr_bal, y_tr_bal)
print('  RandomForest done')

ensemble = VotingClassifier(
    estimators=[('xgb', xgb_final), ('lgbm', lgbm), ('rf', rf_final)],
    voting='soft', n_jobs=-1)
ensemble.fit(X_tr_bal, y_tr_bal)
print('  Ensemble done')

"""Evaluate + Save + End Time"""

print("[8] Evaluating...")
y_arr = np.array(y_test)
t0    = time.time()
preds = ensemble.predict(X_te_sel)
lat   = ((time.time() - t0) * 1e6) / len(y_arr)

acc  = accuracy_score(y_arr, preds)
prec = precision_score(y_arr, preds, average='weighted', zero_division=0)
rec  = recall_score(y_arr, preds, average='weighted', zero_division=0)
f1   = f1_score(y_arr, preds, average='weighted', zero_division=0)

try:
    proba = ensemble.predict_proba(X_te_sel)
    auroc = roc_auc_score(y_arr, proba, multi_class='ovr', average='weighted') \
            if len(le.classes_) > 2 else roc_auc_score(y_arr, proba[:, 1])
except:
    auroc = None

print(f'\n{"="*45}')
print(f'  RESULTS : X-IIoTID')
print(f'{"="*45}')
print(f'  Accuracy  : {acc*100:.4f}%')
print(f'  Precision : {prec*100:.4f}%')
print(f'  Recall    : {rec*100:.4f}%')
print(f'  F1        : {f1*100:.4f}%')
if auroc: print(f'  AUROC     : {auroc:.5f}')
print(f'  Latency   : {lat:.1f} us/sample')
print()
print(classification_report(y_arr, preds,
      target_names=le.classes_.astype(str), zero_division=0))

# Save model
joblib.dump(ensemble,          f'{SAVE_BASE}/ensemble_model.pkl')
joblib.dump(le,                f'{SAVE_BASE}/label_encoder.pkl')
joblib.dump(selected_features, f'{SAVE_BASE}/selected_features.pkl')

pd.DataFrame([{
    'accuracy'  : round(acc*100, 4),
    'precision' : round(prec*100, 4),
    'recall'    : round(rec*100, 4),
    'f1'        : round(f1*100, 4),
    'auroc'     : round(auroc, 5) if auroc else 'N/A',
    'latency_us': round(lat, 1),
    'n_features': best_n,
    'n_classes' : len(le.classes_),
}]).to_csv(f'{SAVE_BASE}/results.csv', index=False)

print(f'Model saved to {SAVE_BASE}')

# Total time
try:
    PIPELINE_END = time.time()
    total_min    = (PIPELINE_END - PIPELINE_START) / 60
    print(f'\n{"="*45}')
    print(f'  TOTAL TIME : {total_min:.1f} min ({total_min/60:.2f} hrs)')
    print(f'{"="*45}')
except:
    print('\nPIPELINE_START not found - session may have restarted')
    print('Results above are still valid and saved to Drive')

import time
print("="*45)
print("  PIPELINE_START is lost due to session restart")
print("  Results are saved in Drive - time is unavailable")
print("="*45)

# Read saved results instead
import pandas as pd
SAVE_BASE = '/content/drive/MyDrive/MyDrive/rosebox_ids/models/x-iiotid'
results = pd.read_csv(f'{SAVE_BASE}/results.csv')
print(results.to_string(index=False))
print("="*45)

